Adding Previous project
shayan1234554321/code_review_microverse pull request #1
Opened 2023-01-16 21:19 UTC by shayan1234554321

2023-01-16 21:43 UTC, shayan1234554321 commented on index.html
> +    <form action="" id="survey-form" >
Good code there !! 🤩
Would you mind, removing the action attribute if you are not using it 🥴

2023-01-16 21:43 UTC, shayan1234554321 commented on index.html
> +      <div id="name">
Hey Shayan, You are performing well. 🤖
But I think using a list ( ul , li tags ) would be a better idea, as I can spot a list here.😉
Eg :
```
<ul>
  <li> *input </li>
</ul>
```

2023-01-16 21:43 UTC, shayan1234554321 commented on js/index.js
> +// Once you have read the above messages, you can delete all comments.
Please remove any unnecessary comments. It might get confusing results. 🥶
But you are doing great there !!
Keep up the good work  🤩

2023-01-16 22:50 UTC, DuaneDave requested changes
Hi @shayan1234554321  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great usage of GitHub inline comments
✔️ Comments are polite and suggestive
✔️ Review uses emoji

## Required Changes ♻️
- Using the GitHub review feature would make the review process more professional and direct (whether the project is approved or not or its just a comment) and as such I suggest that you make use of this feature in this review. [see here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md#how-to-use-github-features)
- I think it would be nice to leave a summary message in the pull request (similar to the one i am leaving on yours, it does not have to be exact). This summary will provide to the student information about a requested change or a congratulation on their achievement in the milestone. Doing so will make the review process more interesting and open to interaction.
- I like the way your comments are tailored, in addition to the polite tone, I think it would be easier for the student to learn from your comments if you include the "why" (why are you requesting the change)
- I recommend being detailed as much as possible when requesting a change, this will help the student understand more about the topic and not just make the change. You can consider adding more explanations or provide a link to an article.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 22:54 UTC, DuaneDave commented on js/index.js
> +// Once you have read the above messages, you can delete all comments.
I suggest that you get a little bit more detailed into why a commented piece of code in the codebase is not good in order to help them learn better.

e.g

Please remove any unnecessary comments from your codebase as they can clutter up th code and make it less readable. 🥶
But you are doing great there !!
Keep up the good work 🤩

2023-01-16 22:58 UTC, DuaneDave commented on index.html
> +      <div id="name">
Specifying to the student why a `ul` is better in this scenario will help him not only make changes but to learn better.


eg


Hey Shayan, You are performing well. 🤖
But I think using a list ( ul , li tags ) would be a better idea, because they make you code well structured and more semantic.😉
Eg :

````````````
<ul>
  <li> *input </li>
</ul>
`````````````

2023-01-16 22:59 UTC, DuaneDave commented on index.html
> +    <form action="" id="survey-form" >
I suggest you get into the 'why' here to help th student learn better 😄

2023-01-17 22:01 UTC, Gambit142 commented on index.html
> +    <form action="" id="survey-form" >
@shayan1234554321, great review, but it can be better. Like the first reviewer said, in your suggestion, you didn't give reasons why the author should make the required changes. Kindly give reasons why the author should do so. For example:

### Bad Suggestion

- **_Why don't you use an article tag here instead of a div?_**

### Good Suggestion

Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible.

In the examples above, the good suggestion gave a detailed reason why you should use `article` tags

#### When making the change to your inline comment, kindly edit the old one. Please don't create a new comment for it. 👍

2023-01-17 22:03 UTC, Gambit142 commented on index.html
> +      <div id="name">
Kindly refer to this comment https://github.com/shayan1234554321/code_review_microverse/pull/1#discussion_r1072874006 for this required change

2023-01-17 22:06 UTC, Gambit142 commented on js/index.js
> +// Once you have read the above messages, you can delete all comments.
Kindly refer to this comment https://github.com/shayan1234554321/code_review_microverse/pull/1#discussion_r1072874006 for this required change

2023-01-17 22:08 UTC, Gambit142 requested changes
Hi @shayan1234554321 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- Good use of inline comments ✔️
- Comments are clear and easy to understand ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
- _Kindly check the comments I made under your suggestions in your review_ 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will resolve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 13:16 UTC, jerryowusu approved these changes
Hi @shayan1234554321 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200w](https://user-images.githubusercontent.com/65233860/213181193-9756394c-1d3e-4e79-b657-31c23eb5065b.gif)


## Highlights
Great effort so far :heavy_check_mark: 
Made changes requested by previous reviewer :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-30 22:44 UTC, closed without merging